description: example job

target:
  service: sing
  name: msrresrchvc
  workspace_name: gcrllama2ws

code:  
  local_dir: /home/t-smantena/deep-fMRI-dataset # path to your code on local machine

environment:
  image: amlt-sing/acpt-2.2.1-py3.10-cuda12.1
  setup:
    # working directory is local_dir under code above
    - pip install -r requirements.txt --user # install requirements from file
    # - pip install . # install a package from the local directory


storage:
  data:
    storage_account_name: internblobdl
    container_name: t-smantena
    mount_dir: /blob_data # path to mount the blob on the remote machine

  
# sku controls the compute you will use
# here are some common ones you may use

# cpu jobs
# 10C3  # 4 cores, 30 GBs mem
# 8C7   # 8 cores, 56 GBs mem
# 8C15  # 15 cores, 120 GBs mem
# 8C30  # 30 cores, 240 GBs mem
# 8C60  # 60 cores, 480 GBs mem

# gpu jobs
# G1-V100 # 1 V100 GPU
# G2-V100 # 2 V100 GPUs
# G1-A100 # 1 A100 GPU


jobs:
- name: sim_2k_sf
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_2k_swf --x 1024 --k 2
- name: sim_4k_sf
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_4k_swf --x 1024 --k 4
- name: sim_8k_sf
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_8k_swf --x 1024 --k 8
- name: sim_16k_sf
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_16k_swf --x 1024 --k 16
- name: sim_32k_sf
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_32k_swf --x 1024 --k 32
- name: sim_2k_df
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_2k_dwf --x 1024 --k 2
- name: sim_4k_df
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_4k_dwf --x 1024 --k 4
- name: sim_8k_df
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_8k_dwf --x 1024 --k 8
- name: sim_16k_df
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_16k_dwf --x 1024 --k 16
- name: sim_32k_df
  process_count_per_node: 1
  sku: 8C60
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature sim_32k_dwf --x 1024 --k 32




storage:
  data:
    storage_account_name: internblobdl
    container_name: t-smantena
    mount_dir: /blob_data # path to mount the blob on the remote machine
