description: example job

target:
  service: sing
  name: msrresrchvc
  workspace_name: gcrllama2ws

code:  
  local_dir: /home/t-smantena/deep-fMRI-dataset # path to your code on local machine

environment:
  image: amlt-sing/acpt-2.3.1-py3.10-cuda12.1
  setup:
    # working directory is local_dir under code above
    - pip install -r requirements.txt --user # install requirements from file
    # - pip install . # install a package from the local directory


storage:
  data:
    storage_account_name: internblobdl
    container_name: t-smantena
    mount_dir: /blob_data # path to mount the blob on the remote machine

  
# sku controls the compute you will use
# here are some common ones you may use

# cpu jobs
# 10C3  # 4 cores, 30 GBs mem
# 8C7   # 8 cores, 56 GBs mem
# 8C15  # 15 cores, 120 GBs mem
# 8C30  # 30 cores, 240 GBs mem
# 8C60  # 60 cores, 480 GBs mem

# gpu jobs
# G1-V100 # 1 V100 GPU
# G2-V100 # 2 V100 GPUs
# G1-A100 # 1 A100 GPU


jobs:
- name: llama_8_b
  process_count_per_node: 1
  sku: G1-A100
  command:
  - python3 encoding/encoding.py --subject UTS03 --feature llama --k 8
# - name: llama2_1024_8
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 1024 --k 8
# - name: llama2_512_8
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 512 --k 8
# - name: llama2_512_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 512 --k 16
# - name: llama2_1024_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 1024 --k 16
# - name: llama2_2048_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 2048 --k 16
# - name: llama2_2048_32
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 2048 --k 32
# - name: llama2_1024_32
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind llama_ind_only --feature_b llama_non_ind_only --x 1024 --k 32

# NEW JOBS
# - name: eng2_512_8
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 512 --k 8
# - name: eng2_512_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 512 --k 16
# - name: eng2_1024_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 1024 --k 16
# - name: eng2_2048_16
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 2048 --k 16
# - name: eng2_2048_32
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 2048 --k 32
# - name: eng2_1024_32
#   process_count_per_node: 1
#   sku: G1-A100
#   command:
#   - python3 encoding/double_encoding.py --subject UTS03 --feature_ind eng_ind_only --feature_b eng_non_ind_only --x 1024 --k 32




